resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: development

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    buildDockerArtifact: false
    preDockerComposePush:
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(Build.SourcesDirectory)/coverage/target/site/jacoco-aggregate/jacoco.xml'
          reportDirectory: '$(Build.SourcesDirectory)/coverage/target/site/jacoco-aggregate'
          pathToSources: '$(Build.SourcesDirectory)'

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master